name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # run at noon & midnight
    - cron:  '0 0,12 * * *'


jobs:
  Build:
    runs-on: macOS-11.0
    environment: Signing
    timeout-minutes: 120
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Import Certificate: Distribution"
        uses: devbotsxyz/import-signing-certificate@main
        with:
          certificate-data: ${{ secrets.DISTRIBUTION_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.DISTRIBUTION_CERTIFICATE_PASSPHRASE }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: SwiftArrow Tests
        run: xcodebuild test -scheme SwiftArrow

      #- name: Parquette Tests
      #  run: xcodebuild test -scheme Parquette

      - name: "Archive"
        uses: devbotsxyz/xcode-archive@v1
        with:
          scheme: "Parquette"

      - name: "Export & Sign Release Build"
        uses: devbotsxyz/xcode-export-archive@master
        with:
          scheme: "Parquette"

      - name: "Notarize Release Build"
        uses: devbotsxyz/xcode-notarize@v1
        with:
          product-path: "Export/Parquette.app"
          appstore-connect-username: ${{ secrets.NOTARIZATION_USERNAME }}
          appstore-connect-password: ${{ secrets.NOTARIZATION_PASSWORD }}

      - name: "Staple Release Build"
        uses: devbotsxyz/xcode-staple@v1
        with:
          product-path: "Export/Parquette.app"

      - name: Package for Distribution
        run: ditto -V -c -k --keepParent "Export/Parquette.app" "Parquette.zip"

      - name: Release app
        uses: softprops/action-gh-release@v1
        with:
          files: Parquette.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
